default_stages: [commit, push]
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        name: Validate Python
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-toml
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-bugbear==22.10.27,
            flake8-builtins==2.0.1,
            flake8-comprehensions==3.10.1,
            flake8-docstrings==1.6.0,
            flake8-rst-docstrings==0.3.0,
            flake8-simplify==0.19.3,
          ]
#   - repo: local
#     hooks:
#     -   id: pytest
#         name: pytest
#         entry: poetry run pytest -cov=src tests/
#         language: system
#         pass_filenames: false
#         # alternatively you could `types: [python]` so it only runs when python files change
#         # though tests might be invalidated if you were to say change a data file
#         always_run: true
#         stages: [push]
